language: python
python:
  - 2.7
  - 3.4
  - 3.5
before_install:
  - pip install coveralls
install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install coverage

script: nosetests -w django_sortable/tests --with-coverage --cover-package=django_sortable
after_success:
  - coveralls
