language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
before_install:
  - pip install coveralls
install:
  - pip install -e .
  - pip install coverage

script: python -m unittest django_sortable.tests
after_success:
  - coveralls
